### PR TITLE
Implement client support for TLS 1.3 0-RTT

### PR DESCRIPTION
**Pull request by kevinis**
Here's my take at implementing TLS 1.3 0-RTT for resumed client sessions. It passes BOGO and works with Cloudflare's TLS 1.3 0-RTT implementation. 

Both Issue [#84](https://github.com/ctz/rustls/issues/84) and the TLS 1.3 draft discuss about the risk of using 0-rtt data. So 0-RTT is by default disabled. A user who wishes to send 0-RTT data to HAProxy or Cloudflare should set `ClientConfig.enable_early_data` and call `ClientSession::write_all()` before the handshake starts. 

Two new Session APIs, `is_in_early_data` and `is_early_data_accepted` are added. `is_in_early_data` returns `true` if any early data is in flight or ready to be sent. This implies a handshake is in process and `is_handshaking()` must be `true`. `is_early_data_accepted` returns `true` if the server has processed the 0-RTT data and the client has sent `EndOfEarlyData`. This API should be called after the handshake is completed.

A `max_early_data_size` field is added to `persist::ClientSessionValue` to indicate the maximum bytes of plaintext that can be sent as early data. This limit is enforced in `Session::send_plain()`. 

The following BOGO test cases are turned on and passed.
PASSED (TLS13-SendTicketEarlyDataInfo)
PASSED (TLS13-SendTicketEarlyDataInfo-Disabled)
PASSED (TLS13-EarlyData-TooMuchData-Client-Sync)
PASSED (TLS13-EarlyData-TooMuchData-Client-Sync-ImplicitHandshake)
PASSED (TLS13-EarlyData-TooMuchData-Client-Sync-SplitHandshakeRecords)
PASSED (TLS13-EarlyData-TooMuchData-Client-Sync-PackHandshake)
PASSED (TLS13-EarlyData-TooMuchData-Client-Async)
PASSED (TLS13-EarlyData-TooMuchData-Client-Async-ImplicitHandshake)
PASSED (TLS13-EarlyData-TooMuchData-Client-Async-SplitHandshakeRecords)
PASSED (TLS13-EarlyData-TooMuchData-Client-Async-PackHandshake)
PASSED (EarlyData-Client-TLS13Draft23)
PASSED (EarlyData-Reject-Client-TLS13Draft23)
PASSED (EarlyData-HRR-Client-TLS13Draft23)
PASSED (EarlyDataWithoutResume-Client-TLS13Draft23)
PASSED (EarlyDataVersionDowngrade-Client-TLS13Draft23)
PASSED (ServerAcceptsEarlyDataOnHRR-Client-TLS13Draft23)
PASSED (EarlyData-Client-VersionAPI-TLS13Draft23)
PASSED (EarlyData-Client-BadFinished-TLS13Draft23)

### CODE REVIEW

**Comment by ctz** [comment]
Thanks, this is great work!

I'd like to keep the early and main application data streams separate though. I'll experiment with some alternative APIs and report back on this PR.

**Comment by ctz** [comment]
I've pushed a commit which uses your work and presents a slightly different API. Could you review it and make sure it meets your requirements?

**Comment by kevinis** [comment]
@ctz The new API looks good to me. In particular I like the new `EarlyDataState` enum and `ClientSessionImpl::write_early_data()`.

**Comment by ctz** [comment]
Thanks. This has been merged now.

**Pull request closed without merging**
