### PR TITLE
WIP: DTLS Support

### PR DESCRIPTION
**Pull request by manuels**
It took me quite some time to find the best way to make the code wort with `TLSMessage` and `DTLSMessage`, but I think I finally found a good solution.
This pull request is here to document the work in progress. Feel free to comment on the code. I will rebase it from time to time until DTLS implementation is finished.

It will close the issue #40.

### CODE REVIEW

**Comment by ctz** [comment]
> ctz approved these changes 35 seconds ago

eh, github is broken. I was going through reviewing commit-by-commit, and now it's approved the whole PR!

**Comment by bkchr** [comment]
@manuels/@ctz is there any chance that this will be merged?

**Comment by manuels** [comment]
@bkchr probably not in the near future. I found wireguard which fits my needs right now. Maybe one day I'll have time to work on DTLS.

**Comment by TimonPost** [comment]
Any progress on this PR would love to see this in action. Currently, I'm forced to work with rust-OpenSSL

**Comment by ctz** [comment]
I'm going to close this. There might be a time in the future where rustls supports DTLS, but at the moment it's not a priority. At the very least I'd like for DTLS1.3 to be completed before I'd consider this again.

**Pull request closed without merging**
