### PR TITLE
Remove SHA-1 signature support.

### PR DESCRIPTION
**Pull request by briansmith**
It has been removed from the latest webpki already.

### CODE REVIEW

**Comment by briansmith** [comment]
@ctz Do you know why the BoGo tests are failing and what I'd need to do to get them working?

**Comment by test9753** [comment]
@briansmith :

The build error seems to be: 
```
FAILED (ClientAuth-Verify-RSA-PKCS1-SHA1-TLS12)
unexpected failure: local error 'remote error: access denied', child error 'none', stdout:
options: ["-port", "34373", "-server", "-key-file", "key.pem", "-cert-file", "cert.pem", "-resume-count", "1", "-handshaker-path", "../../../build/ssl/test/handshaker", "-require-any-client-certificate", "-expect-peer-signature-algorithm", "513", "-enable-all-curves", "-enable-ed25519"]
not checking -handshaker-path ../../../build/ssl/test/handshaker; NYI
not checking -expect-peer-signature-algorithm 513; NYI
not checking -enable-ed25519; NYI
opts Options { port: 34373, server: true, mtu: None, resumes: 1, verify_peer: false, require_any_client_cert: true, offer_no_client_cas: false, tickets: true, resume_with_tickets_disabled: false, queue_data: false, shut_down_after_handshake: false, check_close_notify: false, host_name: "example.com", use_sni: false, send_sct: false, key_file: "key.pem", cert_file: "cert.pem", protocols: [], support_tls13: true, support_tls12: true, min_version: None, max_version: None, server_ocsp_response: [], server_sct_list: [], use_signing_scheme: 0, expect_curve: 0, export_keying_material: 0, export_keying_material_label: "", export_keying_material_context: "", export_keying_material_context_used: false, read_size: 512, quic_transport_params: [], expect_quic_transport_params: [], enable_early_data: false, expect_ticket_supports_early_data: false, expect_accept_early_data: false, expect_reject_early_data: false, queue_data_on_resume: false, expect_version: 0 }
TLS error: PeerMisbehavedError("received unadvertised sig scheme RSA_PKCS1_SHA1")
stderr:
:PEER_MISBEHAVIOUR:
FAILED (ServerAuth-Verify-RSA-PKCS1-SHA1-TLS12)
unexpected failure: local error 'remote error: illegal parameter', child error 'none', stdout:
options: ["-port", "45105", "-resume-count", "1", "-handshaker-path", "../../../build/ssl/test/handshaker", "-expect-peer-signature-algorithm", "513", "-enable-all-curves", "-enable-ed25519"]
not checking -handshaker-path ../../../build/ssl/test/handshaker; NYI
not checking -expect-peer-signature-algorithm 513; NYI
not checking -enable-ed25519; NYI
opts Options { port: 45105, server: false, mtu: None, resumes: 1, verify_peer: false, require_any_client_cert: false, offer_no_client_cas: false, tickets: true, resume_with_tickets_disabled: false, queue_data: false, shut_down_after_handshake: false, check_close_notify: false, host_name: "example.com", use_sni: false, send_sct: false, key_file: "", cert_file: "", protocols: [], support_tls13: true, support_tls12: true, min_version: None, max_version: None, server_ocsp_response: [], server_sct_list: [], use_signing_scheme: 0, expect_curve: 0, export_keying_material: 0, export_keying_material_label: "", export_keying_material_context: "", export_keying_material_context_used: false, read_size: 512, quic_transport_params: [], expect_quic_transport_params: [], enable_early_data: false, expect_ticket_supports_early_data: false, expect_accept_early_data: false, expect_reject_early_data: false, queue_data_on_resume: false, expect_version: 0 }
TLS error: PeerMisbehavedError("received unadvertised sig scheme RSA_PKCS1_SHA1")
stderr:
:PEER_MISBEHAVIOUR:
```
I guess adding the following lines to `bogo/config.json` (in `"DisabledTests"`) might work:
```
    "ClientAuth-Verify-RSA-PKCS1-SHA1-TLS12": "SHA1 is not supported",
    "ServerAuth-Verify-RSA-PKCS1-SHA1-TLS12": "SHA1 is not supported",
```

**Comment by briansmith** [comment]
@test9753 Thanks. I know that we could just disable these tests, but I think a better solution would be to run the tests and ensure that the result is what we expect. I just am not familiar enough with Bogo's configuration system to figure out exactly how to do that yet.

**Comment by ctz** [comment]
This is merged, and I extended bogo to respect the config file for whether a test is expected-pass or expected-fail.

**Pull request closed without merging**
