### PR TITLE
Use IPA for pronunciation guides

### PR DESCRIPTION
**Pull request by jglick**
As a native English speaker I can only interpret the current advice by analogy to https://en.wiktionary.org/wiki/rustle#Pronunciation but that does not really sound right either—silent /t/ really? I can only imagine how an ESL speaker (i.e., most programmers) would interpret this. Please edit or ask me to edit if my guess was not in fact correct.

### CODE REVIEW

**Comment by briansmith** [comment]
Understandable. However, most people can't read IPA, and if the IPA is useful for them, they could just look up the IPA for "rustles" in the dictionary, right? So I'd suggest we don't do this.

**Comment by jglick** [comment]
For a native English speaker it is helpful to say something like

> pronounced like _Russell’s_

(again, if that is in fact the pronunciation!) but for everyone else this just replaces one problem with another.

**Comment by sayrer** [comment]
It's probably better to [delegate this problem to Google](https://user-images.githubusercontent.com/253473/113231236-a5671500-924f-11eb-935c-3e8eaa1cfb2f.png)). I always say "Rust Tee El Ess" in my mind, but the documented pronunciation doesn't bother me.

**Comment by djc** [comment]
Yeah, I think linking to (something that can produce) actual audio is the best solution here.

**Comment by ctz** [comment]
Maybe we should remove the "It's prounounced" sentence altogether? It's ultimately not very important information, and it's certainly not paying its rent for being the second thing someone reads in the readme!

**Comment by sayrer** [comment]
That also sounds good. I remember thinking it was strange when I first read it.

**Comment by ctz** [comment]
Have done that. Thanks for the impetus!

**Pull request closed without merging**
