### PR TITLE
Add Ed25519 support

### PR DESCRIPTION
**Pull request by potatosalad**
See #292 for the original draft pull request.

This is a pull request for adding Ed25519 support.

See #52 for more information.

_Notes_

* Some `bogo` related tests are still failing.
* The OpenSSL related commands (like `test-ca/build-a-pki.sh`) depend on [OpenSSL version 1.1.1](https://www.openssl.org/news/openssl-1.1.1-notes.html).  On macOS, for example, prefixing `cargo test` commands with `OPENSSL_DIR="$(brew --prefix openssl@1.1)"` will allow the tests to pass.

### CODE REVIEW

**Comment by ctz** [comment]
Thanks for working on this!

I had a quick look at the remaining bogo failures: at least _some_ of these are happening because the test wants to see ed25519 working with TLS1.2. That currently won't work because all the implemented ciphersuites (say, `TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256`) will be removed from consideration by the server, leaving zero TLS1.2 ciphersuites to select from.

I suggest we keep this as a TLS1.3-only feature, and perhaps just skip these tests?

**Comment by kim** [comment]
@ctz Thanks for the pointer. 

I only found one test case which is expected to succeed. Since I can't seem to get the bogo suite to run locally, have to wait until new build logs are availabe...

**Comment by potatosalad** [comment]
@kim I pushed up a few other bogo related exemptions.  Locally, everything now passes for me except `Ed25519DefaultDisable-NoAccept` and `Ed25519DefaultDisable-NoAdvertise`.

I'm not sure whether the config settings are appropriate or not or if they are a sign of an actual implementation bug.

**Comment by kim** [comment]
> I suggest we keep this as a TLS1.3-only feature

Do you mean that it should be an error to use an ed25519 key if the protocols include anything below 1.3?

**Comment by ctz** [comment]
This is merged now. Thanks a lot for the hard work on this!

**Pull request closed without merging**
