### PR TITLE
Set up formatting in CI

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Comment by ctz** [comment]
I'd like to get #443, #537, #547 merged before attending to this.  But it seems straightforward to merge -- taking e1150e2 as-is and remaking d47c1ee

**Comment by djc** [comment]
I'm also generally happy to rebase my own PRs on top of this. Thanks for following up!

**Comment by djc** [comment]
Should we just get this merged? It will always be a nuisance, but I'll make a standing offer to rebase anyone's branches.

**Comment by djc** [comment]
Rebased this on current main. Now seems like a pretty good time to land this?

**Pull request merged**
