### PR TITLE
Add Ed25519 support

### PR DESCRIPTION
**Pull request by potatosalad**
This is a work-in-progress/draft pull request for adding Ed25519 support.

See #52 for more information.

_Notes_

* Some `bogo` related tests are still failing.
* The OpenSSL related commands (like `test-ca/build-a-pki.sh`) depend on [OpenSSL version 1.1.1](https://www.openssl.org/news/openssl-1.1.1-notes.html).  On macOS, for example, prefixing `cargo test` commands with `OPENSSL_DIR="$(brew --prefix openssl@1.1)"` will allow the tests to pass.

### CODE REVIEW

**Comment by kim** [comment]
@potatosalad @tyrchen: is there anything I could help with to move this forward? I'm quite interested in getting ed25519 support into upstream.

**Comment by potatosalad** [comment]
@kim So, it's been a few months since I've messed around with this, but if I remember correctly the problem was I couldn't figure out how to get the Azure Pipelines stuff working properly for CI/CD because it depends on OpenSSL in order to build/run some of the PKI related functions to compare Rustls output against OpenSSL.  Ed25519 was added to OpenSSL in version 1.1.1 (I believe) and I couldn't figure out how to get it to work at the time (you'll notice the last 3 commits prefixed with "WIP" are solely related to my attempts to get the CI/CD to work properly).

Beyond that, I believe this is ready to be reviewed and/or integrated.

**Comment by kim** [comment]
@potatosalad Thanks. If it's only about taming the build infra, I'd be happy to take a stab at it. I think you would have to grant me push access to your fork, though. Or else, I'd need to open another PR here with your changes.

**Comment by potatosalad** [comment]
@kim Access granted 😄

**Comment by kim** [comment]
Ok, so ... nothing happens? Not sure what to make of this.

**Comment by potatosalad** [comment]
No idea, should we close this PR and open a new one?  Not sure why the hooks don't seem to be firing.

**Comment by kim** [comment]
Yeah worth a try.

The travis logs are still available, so I could peek at the bogo failures. Will try to get the suite up locally and investigate the failures (tomorrow though, as it’s quite late over here already).

**Comment by Darkspirit** [comment]
Try closing and reopening this PR.

**Comment by potatosalad** [comment]
@kim @Darkspirit Created a fresh, rebased version of this PR in #340 and the CI/CD appears to be working again.

**Pull request closed without merging**
