### PR TITLE
Add SNI to server session & expose it to the application.

### PR DESCRIPTION
**Pull request by briansmith**
See the individual commit messages for details.

### CODE REVIEW

**Comment by briansmith** [comment]
I expect to write some BoGo tests for this, but they aren't ready yet for non-technical reasons. I expect I'll submit them directly upstream.

**Comment by ctz** [comment]
looks like this is failing tests because bogo uses fictional SNI and weird certificates. i'm going to regenerate all the certs before running tests

**Comment by briansmith** [comment]
@ctz Would it be better if I just updated BoGo to use reasonable certificates by default?

**Comment by briansmith** [comment]
I will rebase this on top of #99. In the meantime, I'll work on updating BoGo to use certs that will work with this.

**Comment by ctz** [comment]
> Would it be better if I just updated BoGo to use reasonable certificates by default?

Yes, that would be ideal.

**Comment by ctz** [comment]
In the meantime I have this merged, albeit with the check moved after HRR for TLS1.3 and some extra tests.

**Pull request merged**
