### PR TITLE
Show ALPN upgrade protocol as string in debug logs

### PR DESCRIPTION
**Pull request by dermesser**
This is an almost trivial request, but it would have helped me as a TLS noob to figure out what the ALPN upgrade does here.

The chosen conversion avoids allocations. Downside: If the ALPN string is ever not valid UTF-8, it will be invisible in the logs. However, [RFC 7301](https://tools.ietf.org/html/rfc7301#section-6) gives some expectation that the ALPN protocol strings are and will consist of characters in the ASCII subset.

Before:
```
[2020-10-24T16:00:32Z DEBUG rustls::client::hs] ALPN protocol is Some([104, 50])
```

After: 
```
[2020-10-24T16:00:32Z DEBUG rustls::client::hs] ALPN protocol is Some("h2")
```

### CODE REVIEW

**Comment by Ralith** [comment]
We shouldn't report that the ALPN is "" when it's not.

**Comment by djc** [comment]
Maybe a utf8_lossy() conversion would be fitting here?

**Comment by dermesser** [comment]
Good point. This results in an allocation, but -- if I understand the `debug!()` respectively `log!()` macros correctly -- only at a sufficient debugging level. For the case that the ALPN string is not a printable string, it is also printed in the way that rustls did before this PR.

**Comment by djc** [comment]
LGTM. This is kind of fixing a regression from when I changed ALPN protocols to be stored as bytes instead of str.

**Comment by ctz** [comment]
Thanks, I've merged this with a minor change -- reusing the fmt::Debug handler we have for printing certificate contents. This prints u8 slices as ascii with C-style escapes if needed.

**Pull request closed without merging**
