### PR TITLE
Bump mio to 0.7

### PR DESCRIPTION
**Pull request by linkmauve**
Closes #344.

### CODE REVIEW

**Comment by ctz** [comment]
Thanks!

**Comment by ctz** [comment]
Ah, apologies, I had to back this out -- it seems to be causing random hangs in tlsclient (as seen in https://dev.azure.com/ctz99/ctz/_build/results?buildId=480&view=logs&j=93d8c60c-7e81-574d-6967-9afc3f308620 and locally).

**Comment by linkmauve** [comment]
Any idea why?  I couldn’t figure it out, as it doesn’t seem to happen locally.

**Comment by ctz** [comment]
I've worked this out and reinstated the merge: removing reregister calls meant mio wasn't informed of our changing IO requirements after messages were sent/received.

**Comment by ctz** [comment]
Hm, actually that's fixed it on linux/mac but it's still broken on windows :(

**Comment by ctz** [comment]
(that is also now fixed)

**Pull request merged**
