### PR TITLE
Refactor server EMS state.

### PR DESCRIPTION
**Pull request by sayrer**
Removed `using_ems` from the server HandshakeDetails. I think I got this right wrt to TLS 1.3, but please check. @djc @briansmith @ctz.

### CODE REVIEW

**Comment by sayrer** [comment]
It looks like the server TLS 1.3 code depends on `using_ems` in a way that it shouldn't, which was masked by `HandshakeDetails` previously. I'll have to take a look at hs::ClientHello.

**Comment by sayrer** [comment]
I think what I have written here has been correct the whole time, because none of the `into_tls13*` methods have `using_ems` in their parameter list (makes sense).

I think this patch is an improvement as-is, but points at a need to statically disentangle TLS 1.2 and TLS 1.3, in the `hs.rs` structs that have `into` methods for both.

**Comment by sayrer** [comment]
The one failure here is in bogo/, but it passes here with the work in #558 and #565.

**Comment by djc** [comment]
LGTM, thanks!

**Pull request merged**
